DROP TABLE IF EXISTS user;
CREATE TABLE user (
  id            INT(11) NOT NULL AUTO_INCREMENT COMMENT '用户编号',
  nickname      VARCHAR(255) NOT NULL COMMENT '用户昵称',
  create_time   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  deleted       SMALLINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  PRIMARY KEY (id)
);