spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
#    url: jdbc:h2:mem:product
#    username: root
#    password: test
  datasource:
    url: jdbc:mysql://localhost:3307/flash_sale?useSSL=false
    username: root
    password: i-Sprint2011
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 192.168.232.128
    port: 6379
    password:
    timeout: 200
    #    cluster:
    #      nodes:
    #        - 192.168.232.128:9011
    #        - 192.168.232.128:9012
    #        - 192.168.232.128:9013
    #        - 192.168.232.128:9014
    #        - 192.168.232.128:9015
    #        - 192.168.232.128:9016
    #          max-redirects: 3
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 4

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: io.github.zhenyed.api.product.dataobject
  global-config:
    db-config:
      id-type: auto
