server:
  port: 8001

spring:
  application:
    name: flash-sale-eureka
  profiles:
    active: default

#eureka:
#  server:
#    enable-self-preservation: false
#  instance:
#    hostname: localhost
#    lease-expiration-duration-in-seconds: 60
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

management:
  endpoint:
    web:
      exposure:
        include: '*'
---
server:
  port: 8001

spring:
  application:
    name: flash-sale-eureka
  profiles:
    active: peer01

eureka:
  instance:
    hostname: ${server.peer01}
    prefer-ip-address: false
    instance-id: ${server.peer01}:${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    use-dns-for-fetching-service-urls: false
    serviceUrl:
      defaultZone: http://${server.peer02}:${server.port}/eureka/,http://${server.peer03}:${server.port}/eureka/

management:
  endpoint:
    web:
      exposure:
        include: '*'
---
server:
  port: 8001

spring:
  application:
    name: flash-sale-eureka
  profiles:
    active: peer02

eureka:
  instance:
    hostname: ${server.peer02}
    prefer-ip-address: false
    instance-id: ${server.peer02}:${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    use-dns-for-fetching-service-urls: false
    serviceUrl:
      defaultZone: http://${server.peer01}:${server.port}/eureka/,http://${server.peer03}:${server.port}/eureka/

management:
  endpoint:
    web:
      exposure:
        include: '*'
---
server:
  port: 8001

spring:
  application:
    name: flash-sale-eureka
  profiles:
    active: peer03

eureka:
  instance:
    hostname: ${server.peer03}
    prefer-ip-address: false
    instance-id: ${server.peer03}:${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    use-dns-for-fetching-service-urls: false
    serviceUrl:
      defaultZone: http://${server.peer01}:${server.port}/eureka/,http://${server.peer02}:${server.port}/eureka/

management:
  endpoint:
    web:
      exposure:
        include: '*'