server:
  port: 8003

spring:
  application:
    name: flash-sale-eureka
  profiles:
    active: peer3

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/,http://localhost:8001/eureka/
