server:
  port: 8001

spring:
  application:
    name: flash-sale-eureka
  profiles:
    active: peer1

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/,http://localhost:8003/eureka/