apiVersion: v1
kind: Service
metadata:
  name: eureka-nodeport
  labels:
    app: eureka-nodeport
spec:
  type: NodePort
  ports:
    - name: server
      port: 8001
      targetPort: 8001
      nodePort: 31011
  selector:
    app: eureka