server:
  port: 8080

spring:
  application:
    name: flash-sale-gateway
  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#    sentinel:
#      transport:
#        port: 8721
#        dashboard: localhost:8002
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

